name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Run Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4.1.7

      - name: Setup Node.JS
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20

      - name: Set up PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Jest GitHub Action
        uses: willcaul/jest-github-action@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MONGODB_URL: ${{ vars.MONGODB_URL }}
          KAFKA_ENDPOINT: ${{ vars.KAFKA_ENDPOINT }}
          KAFKA_USERNAME: ${{ vars.KAFKA_USERNAME }}
          KAFKA_PASSWORD: ${{ vars.KAFKA_PASSWORD }}
        with:
          test-command: "pnpm test"
